### ISSUE TITLE
Initial install.py fails

### ISSUE THREAD

**Issue by connortechnology** [baudneo/zomi-client#3]
04/13/24 08:59:50.0788 install_client[1293147] WARNING install:511 -> Data directory /opt/zomi/client already exists!
Traceback (most recent call last):
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 1394, in <module>
    main()
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 850, in main
    install_dirs(
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 519, in install_dirs
    create_dir(_path, ml_user, ml_group, perms)
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 389, in create_dir
    chown_mod(path, user, group, mode)
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 377, in chown_mod
    chown(path, user, group)
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 362, in chown
    user = pwd.getpwnam(user).pw_uid
KeyError: "getpwnam(): name not found: 'imoz'"

This is because I didn't specify --user.  imoz doesn't exist on my system of course.  So perhaps it should default to www-data? And perhaps a useful error message instead of a traceback.

After figuring that one out:

04/13/24 09:05:10.0113 install_client[1295093] INFO install:978 -> Creating symlinks for event start/stop commands: /usr/local/bin will contain zomi-ESC (shell helper) zomi-eventproc (python script)
Traceback (most recent call last):
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 1395, in <module>
    main()
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 877, in main
    do_install()
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 1006, in do_install
    create_("secrets", cfg_dir / "secrets.yml")
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 1137, in create_
    envsubst_out = envsubst(src.read_text(), _ENV)
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 1132, in envsubst
    return _.sub(string, env=env, strict=strict)
  File "/home/iconnor/sandbox/zomi-client/examples/install.py", line 1078, in sub
    b: str = _extended_re.sub(self._repl_extended_env_var, a)
TypeError: sequence item 11: expected str instance, int found

**Comment by baudneo** [comment]
I think its fixed.

**Comment by baudneo** [comment]
AFAIK this is fixed, please let me know and re-open if it is not.
